#########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ayatana-indicator-notifications
    - clang
    - gcc
    - git
    - make
    - startup-notification
    - which
    - cmake
    - cmake-extras
    - intltool
#    - libayatana-common
    - gobject-introspection
#    - liblomiri-url-dispatcher
    - vala
    - glib2
    - systemd

  debian:
    # Useful URL: https://salsa.debian.org/debian-ayatana-team/ayatana-indicator-notifications
    - clang
    - clang-tools
    - g++
    - cppcheck
    - git
    - cmake
    - cmake-extras
    - intltool
#    - libayatana-common-dev
    - gobject-introspection
    - libgirepository1.0-dev
    - liblomiri-url-dispatcher-dev
    - valac
    - libglib2.0-dev
    - systemd

  ubuntu:
    - clang
    - clang-tools
    - g++
    - git
    - cmake
    - cmake-extras
    - intltool
#    - libayatana-common-dev
    - gobject-introspection
    - libgirepository1.0-dev
    - liblomiri-url-dispatcher-dev
    - valac
    - libglib2.0-dev
    - systemd

  ubuntu:focal:
    - clang
    - clang-tools
    - g++
    - git
    - cmake
    - cmake-extras
    - intltool
#    - libayatana-common-dev
    - gobject-introspection
    - libgirepository1.0-dev
#    - liblomiri-url-dispatcher-dev
    - valac
    - libglib2.0-dev
    - systemd

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:
  - cd ${START_DIR}
  - if [ ! -d libayatana-common-build ]; then
  -     git clone --depth 1  https://github.com/AyatanaIndicators/libayatana-common.git libayatana-common-build
  - fi
  - cd libayatana-common-build
  - cmake . -DCMAKE_INSTALL_PREFIX=/usr
  - make
  - make install
  - cd -
  - rm -Rf libayatana-common-build/

build_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     export CFLAGS+=" -Wsign-compare -Wunused-parameter"
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi
  -
  - if [ -e ./CMakeLists.txt ]; then
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS cmake . -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DENABLE_TESTS=ON
  -     else
  -         scan-build $CHECKERS cmake . -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON
  -     fi
  - else
  -     exit 1
  - fi
  -
  - if [ $CPU_COUNT -gt 1 ]; then
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make -j $CPU_COUNT
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
#  - XVFB_RUN="$(which xvfb-run || true)"
#  - if [ ${DISTRO_NAME} == "debian" ];then
#  -     if [ -e ./CMakeLists.txt ]; then
#  -         ${XVFB_RUN} env CTEST_OUTPUT_ON_FAILURE=1 make test
#  -     fi
#  - fi
